### ISSUE TITLE
Able to add feature for listing all update version for certain model?

### ISSUE THREAD

**Issue by sabpprook** [oxygen-updater/oxygen-updater-backend#21]
The purpose is to get previous OTA (full) file, currently the API is only provide downward querying or latest update data.

**Comment by adhirajsinghchauhan** [comment]
This backend is primarily for the Android app, and it's not intended to be used freely by others. Occasionally we allow developers to use our APIs, but it's on good faith.

There's not much point in displaying older OTA packages in the app, since they can't be installed anyway due to standard Android security measures.

In very rare cases where users are already on an older version, and want to update to an intermediate one, we provide direct downloads links over email/Discord. Otherwise members of our team send XDA these links, and maintain "repo threads" there as well.

What's your use-case?

**Comment by sabpprook** [comment]
I want to create fastboot flashable firmware that extarct from full OTA package for Oneplus 7T and I will need the OTA package is on latest Android 11 / Android 10 version, so I'm wondering is there a way to get all update versions and download links for it.

Thanks for your reply, I'll find the OTA packages on XDA fourm.

**Comment by adhirajsinghchauhan** [comment]
Alright, closing this issue. If you need help with anything, reach out to us and we can collaborate.
